server:
  image: node:6
  command: npm run watch
  working_dir: /app/server
  volumes:
    - ./server:/app/server
  environment:
    PORT: 3000
    CONNECTION_STRING_DEV: postgres://user:password@db/db
  ports:
    - "3000:3000"
    - "5858:5858"
  links:
    - db
db:
  image: postgres
  expose:
    - 5432
  environment:
    POSTGRES_PASSWORD: password
    POSTGRES_USER: user
    POSTGRES_DB: db
